import React from "react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Locale, locales } from "@/lib/i18n/constants";
import "../globals.css";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export async function generateStaticParams() {
  return locales.map((locale) => ({ lang: locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: Locale };
}>) {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <body className={`${poppins.className} antialiased`}>{children}</body>
    </html>
  );
}
